<?php

defined( 'ABSPATH' ) or die(':)');



function child_sponsorship_add_menu_page() {
    add_menu_page(
        __('Child sponsporship', 'child-sponsorship'),
        __('Child sponsporship', 'child-sponsorship'),
        'manage_options',
        'manage-child-sponsorship',
        '',
        'dashicons-carrot'
    );
}
add_action( 'admin_menu', 'child_sponsorship_add_menu_page' );

function manage_child_sponsorship_callback(){
    global $wpdb;
    $table_name = $wpdb->prefix . "child_sponsorship"; 

    if (isset($_POST['newsubmit'])) {

        if ( ! function_exists( 'wp_handle_upload' ) ) {
            require_once( ABSPATH . 'wp-admin/includes/file.php' );
        }
        
        $uploadedfile = $_FILES['child_photo'];
        $upload_overrides = array( 'test_form' => false );
        $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
        
        if ( $movefile && ! isset( $movefile['error'] ) ) {
            
            $url = $movefile["url"];
            $name = $_POST['name'];
            $description = $_POST['description'];
            $location = $_POST['location'];
            $stripename = $_POST['stripename'];

            $price = $_POST['price'];
       $wpdb->query("INSERT INTO $table_name(name,description,url,price,location,stripename) VALUES('$name','$description', '$url', '$price', '$location', '$stripename')");


        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            echo $movefile['error'];
        }

  
    //   echo "<script>location.replace('admin.php?page=manage-child-sponsorship');</script>";
    }





    if (isset($_POST['uptsubmit'])) {
      $id = $_POST['id'];
      $name = $_POST['name'];
      $stripename = $_POST['stripename'];
      $description = $_POST['description'];
      $location = $_POST['location'];
      $price = $_POST['price'];


      $uploadedfile = $_FILES['child_photo'];
      $upload_overrides = array( 'test_form' => false );
      $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
      
      if ( $movefile && ! isset( $movefile['error'] ) ) {
        $url = $movefile["url"]; 
        $urlsql = ", url = '$url'";
      }

     // echo "UPDATE $table_name SET name='$name',description='$email' $urlsql WHERE user_id='$id'";exit;
      $wpdb->query("UPDATE $table_name SET name='$name',price='$price', description='$description' ,location='$location' , stripename='$stripename' $urlsql WHERE id='$id'");
      echo "<script>location.replace('admin.php?page=manage-child-sponsorship');</script>";
    }

    if (isset($_GET['del'])) {
      $del_id = $_GET['del'];
      $wpdb->query("DELETE FROM $table_name WHERE id='$del_id'");
      echo "<script>location.replace('admin.php?page=manage-child-sponsorship&deleted=1');</script>";
    }
    if (isset($_GET['deleted'])) {
      echo '<div class="warning">Record deleted. Please make sure to delete the associated SKU product in Stripe dashboard.</div>';
    }

    ?>
    <div class="wrap">
      <h2>Child Sponsorship</h2>
      
      <?php
        if (isset($_GET['upt'])) {
          $upt_id = $_GET['upt'];
          $result = $wpdb->get_results("SELECT * FROM $table_name WHERE id='$upt_id'");
          foreach($result as $print) {
            $name = $print->name;
            $description = $print->description;
           
          }
          echo "
         
              <form class='child-form' action='' method='post' enctype='multipart/form-data'>
                
                  <input type='hidden' name='id' value='$print->id'>
                  <div><input type='text'  placeholder='Name' required id='uptname' name='name' value='$print->name'></div>
                  <div><input type='text'  placeholder='Stripename' id='' required name='stripename' value='$print->stripename'></div>
                  <div><input type='text'  placeholder='Location' id='' required name='location' value='$print->location'></div>
                  <div><textarea required  placeholder='Description' name='description'>$print->description</textarea></div>
                  <div><input required  placeholder='Price' type='number' name='price' value='$print->price'/></div>

                  <div> <img src='$print->url' width='250px'/>
                  <br /> <input type='file'    name='child_photo'> </div>
                  <div><button id='uptsubmit' name='uptsubmit' type='submit'>UPDATE</button> <a href='admin.php?page=manage-child-sponsorship'><button type='button'>CANCEL</button></a></div>

              </form>
          ";
        } else {
      ?>
       

       <form class='child-form' action="" method="post" enctype="multipart/form-data">
              <div><input type="text" placeholder="Name" required id="newname" name="name"></div>
              <div><input type="text" placeholder="SKU" required  name="stripename">
              <br />
              <i>Needed for stripe as a product key, should be unique, no special chars </i>
            </div>
            <div><input type="text" placeholder="Location" required id="" name="location"></div>

              <div><textarea required  placeholder="description"  name="description"></textarea></div>
              <div><input required type='number'  placeholder="price"  name='price' /></div>
              <div><input type="file" required name="child_photo"></div>
              <div><button class="btn"  id="newsubmit" name="newsubmit" type="submit">Add</button></div>
          </form>
         
          <table class='wp-list-table widefat striped'>
            <thead>
              <tr>
                <th >Name</th>
                <th >Stripename(SKU)</th>
                <th >Amount</th>
                <th >Photo</th>
                <th >Actions</th>
                <th >Donor</th>


              </tr>
            </thead>


          <?php
            $result = $wpdb->get_results("SELECT * FROM $table_name");
            foreach ($result as $print) {
              echo "
                <tr>
                  <td >$print->name</td>
                  <td >$print->stripename</td>
                  <td> $print->price </td>
                  <td> <img src='$print->url' width='200'/></td>
                  <td ><a href='admin.php?page=manage-child-sponsorship&upt=$print->id'>Edit</a> <a href='admin.php?page=manage-child-sponsorship&del=$print->id'><button type='button'>DELETE</button></a></td>
                  <td> $print->donor_user</td>
                </tr>
              ";
            }
          ?>
         
      </table>
      <?php } ?>
      <br>
      <br>
     
    </div><?php

}
function child_sponsorship_add_submenu() {
    add_submenu_page(
    	"manage-child-sponsorship",
    	__('Sponsorship', 'child-sponsorship'), __('General Settings', 'child-sponsorship'),
    	'manage_options',
    	'manage-child-sponsorship',
    	'manage_child_sponsorship_callback'
    );

    // add_submenu_page(
    //     "manage-child-sponsorship",
    //     __('Video PopUp on Page Load', 'child-sponsorship'), __('On Page Load', 'video-popup'),
    //     'manage_options',
    //     'manage-child-sponsorship',
    //     'manage_child_sponsorship_callback'
    // );

  
}
add_action('admin_menu', 'child_sponsorship_add_submenu');


function child_sponsorship_install () {
    global $wpdb;
 
    $table_name = $wpdb->prefix . "child_sponsorship"; 

        
        $charset_collate = $wpdb->get_charset_collate();
    
        $sql = "CREATE TABLE `live_child_sponsorship` (
          `id` mediumint(9) NOT NULL AUTO_INCREMENT,
          `time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
          `name` tinytext  NOT NULL,
          `stripename` varchar(255)  NOT NULL,
          `description` text   NOT NULL,
          `url` varchar(500)   NOT NULL DEFAULT '',
          `price` int(4) NOT NULL,
          `donor_user` varchar(255)   DEFAULT NULL,
          `location` varchar(500)   DEFAULT NULL,
          PRIMARY KEY  (id)
        ) ;
        
        ";
    
        require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
        dbDelta( $sql );
    
 }

 wp_enqueue_style( 'cs-admin-style', plugins_url('/css/settings.css', __FILE__), array(), time(), "all" );

