<?php

defined( 'ABSPATH' ) or die(':)');



function child_sponsorship_add_menu_page() {
    add_menu_page(
        __('General Settings', 'child-sponsorship'),
        __('Child sponsporship', 'child-sponsorship'),
        'manage_options',
        'manage-child-sponsorship',
        '',
        'dashicons-carrot'
    );
}
add_action( 'admin_menu', 'child_sponsorship_add_menu_page' );

function manage_child_sponsorship_callback(){
    global $wpdb;
    $table_name = $wpdb->prefix . "child_sponsorship"; 

    if (isset($_POST['newsubmit'])) {

        if ( ! function_exists( 'wp_handle_upload' ) ) {
            require_once( ABSPATH . 'wp-admin/includes/file.php' );
        }
        
        $uploadedfile = $_FILES['child_photo'];
        $upload_overrides = array( 'test_form' => false );
        $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
        
        if ( $movefile && ! isset( $movefile['error'] ) ) {
            
            $url = $movefile["url"];
            $name = $_POST['name'];
            $email = $_POST['description'];
       $wpdb->query("INSERT INTO $table_name(name,description,url) VALUES('$name','$description', '$url')");


        } else {
            /**
             * Error generated by _wp_handle_upload()
             * @see _wp_handle_upload() in wp-admin/includes/file.php
             */
            echo $movefile['error'];
        }

  
    //   echo "<script>location.replace('admin.php?page=manage-child-sponsorship');</script>";
    }





    if (isset($_POST['uptsubmit'])) {
      $id = $_POST['id'];
      $name = $_POST['name'];
      $description = $_POST['description'];


      $uploadedfile = $_FILES['child_photo'];
      $upload_overrides = array( 'test_form' => false );
      $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
      
      if ( $movefile && ! isset( $movefile['error'] ) ) {
        $url = $movefile["url"]; 
        $urlsql = ", url = '$url'";
      }

     // echo "UPDATE $table_name SET name='$name',description='$email' $urlsql WHERE user_id='$id'";exit;
      $wpdb->query("UPDATE $table_name SET name='$name',description='$description' $urlsql WHERE id='$id'");
      echo "<script>location.replace('admin.php?page=manage-child-sponsorship');</script>";
    }

    if (isset($_GET['del'])) {
      $del_id = $_GET['del'];
      $wpdb->query("DELETE FROM $table_name WHERE id='$del_id'");
      echo "<script>location.replace('admin.php?page=manage-child-sponsorship');</script>";
    }
    ?>
    <div class="wrap">
      <h2>Child Sponsorship</h2>
      <table class="wp-list-table widefat striped">
        <thead>
          <tr>
            <th >User ID</th>
            <th >Name</th>
            <th >Description</th>
            <th >Photo</th>
            <th >Actions</th>
          </tr>
        </thead>
        <tbody>
          <form action="" method="post" enctype="multipart/form-data">
            <tr>
              <td><input type="text" required id="newname" name="name"></td>
              <td><textarea required name="description"></textarea></td>
              <td><input type="file" required name="child_photo"></td>
              <td><button id="newsubmit" name="newsubmit" type="submit">Add</button></td>
            </tr>
          </form>
          <?php
            $result = $wpdb->get_results("SELECT * FROM $table_name");
            foreach ($result as $print) {
              echo "
                <tr>
                  <td >$print->time</td>
                  <td >$print->name</td>
                  <td>$print->description</td>
                  <td> <img src='$print->url' width='200'/></td>
                  <td ><a href='admin.php?page=manage-child-sponsorship&upt=$print->id'>Edit</a> <a href='admin.php?page=manage-child-sponsorship&del=$print->id'><button type='button'>DELETE</button></a></td>
                </tr>
              ";
            }
          ?>
        </tbody>  
      </table>
      <br>
      <br>
      <?php
        if (isset($_GET['upt'])) {
          $upt_id = $_GET['upt'];
          $result = $wpdb->get_results("SELECT * FROM $table_name WHERE id='$upt_id'");
          foreach($result as $print) {
            $name = $print->name;
            $description = $print->description;
           
          }
          echo "
          <table class='wp-list-table widefat striped'>
            <thead>
              <tr>
                <th >User ID</th>
                <th >Name</th>
                <th >Description</th>
                <th >Photo</th>
                <th >Actions</th>
              </tr>
            </thead>
            <tbody>
              <form action='' method='post' enctype='multipart/form-data'>
                <tr>
                  <td >$print->id <input type='hidden' name='id' value='$print->id'></td>
                  <td ><input type='text' id='uptname' name='name' value='$print->name'></td>
                  <td ><textarea required name='description'>$description</textarea></td>
                  <td > <img src='$print->url' width='300px'/> <input type='file'    name='child_photo'> </td>
                  <td ><button id='uptsubmit' name='uptsubmit' type='submit'>UPDATE</button> <a href='admin.php?page=manage-child-sponsorship'><button type='button'>CANCEL</button></a></td>
                </tr>
              </form>
            </tbody>
          </table>";
        }
      ?>
    </div><?php

}
function child_sponsorship_add_submenu() {
    add_submenu_page(
    	"manage-child-sponsorship",
    	__('Video PopUp General Settings', 'child-sponsorship'), __('General Settings', 'child-sponsorship'),
    	'manage_options',
    	'manage-child-sponsorship',
    	'manage_child_sponsorship_callback'
    );

    add_submenu_page(
        "manage-child-sponsorship",
        __('Video PopUp on Page Load', 'child-sponsorship'), __('On Page Load', 'video-popup'),
        'manage_options',
        'manage-child-sponsorship',
        'manage_child_sponsorship_callback'
    );

    // add_submenu_page(
    // 	"video_popup_general_settings",
    // 	__('Video PopUp Shortcode', 'video-popup'), __('Shortcode Usage', 'video-popup'),
    // 	'manage_options',
    // 	'video_popup_shortcode',
    // 	'video_popup_shortcode_callback'
    // );
}
add_action('admin_menu', 'child_sponsorship_add_submenu');


function child_sponsorship_install () {
    global $wpdb;
 
    $table_name = $wpdb->prefix . "child_sponsorship"; 

        
        $charset_collate = $wpdb->get_charset_collate();
    
        $sql = "CREATE TABLE $table_name (
            id mediumint(9) NOT NULL AUTO_INCREMENT,
            time datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
            name tinytext NOT NULL,
            text text NOT NULL,
            url varchar(55) DEFAULT '' NOT NULL,
            PRIMARY KEY  (id)
        ) $charset_collate;";
    
        require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
        dbDelta( $sql );
    
 }


/*
function video_popup_meta_row_style(){
	wp_enqueue_style( 'video-popup-meta-row-style', plugins_url('/css/meta-row-style.css', __FILE__), array(), time(), "all" );

	if( isset($_GET['page']) and ($_GET['page'] == 'video_popup_general_settings' or $_GET['page']== 'video_popup_shortcode' or $_GET['page']== 'video_popup_on_pageload') ){
		wp_enqueue_style( 'video-popup-settings-style', plugins_url('/css/settings.css', __FILE__), array(), time(), "all" );
	}

    if( !get_option('vp_green_bg_menu') ) {
        wp_enqueue_style( 'video-popup-green-menu', plugins_url('/css/green-menu.css', __FILE__), array(), time(), "all" );
    }
}
add_action('admin_enqueue_scripts', 'video_popup_meta_row_style');








function video_popup_extension_update_checker(){
    if( get_option('vp_extension_update_checker_105') === false ){
        if( get_option('vp_extension_update_checker_104') === true ){
            delete_option('vp_extension_update_checker_104');
        }
        $cache_time = 3600 * 24 * 7;
        delete_transient('vp-prm-alobaidi');
        update_option('vp_extension_update_checker_105', '1');
        update_option('vp_prm_alobaidi', 'has_up');
        set_transient('vp-prm-alobaidi', 'has_up', $cache_time);
    }
}
add_action('admin_init', 'video_popup_extension_update_checker');


require_once dirname( __FILE__ ). '/settings.php';

require_once dirname( __FILE__ ). '/on-pageload.php';

require_once dirname( __FILE__ ). '/shortcode-usage.php';